### ISSUE TITLE
Provide an easy way to exclude some tests/test files

### ISSUE THREAD

**Issue by pravi** [geemus/shindo#18]
Currently there is no easy way to exclude some tests like rspec or minitest. For example, in fog-aws, we want to exclude some tests in debian package, but the only way we could find was to remove those files. lib/shindo/rake just calls shindo command. Would it be possible to support some exclusion patterns? In case fo fog-aws, we had to disable tests that fail with fog-core 2.1.0 and works only with fog-core 2.1.2. We cannot use fog-core 2.1.2 because fog-google is not yet compatible with it.

**Comment by geemus** [comment]
We could probably manage something. What do you imagine the interface would look like? Would you be able to help work on the implementation? Thanks!

**Comment by pravi** [comment]
If we can pass a 'FileList' in a rake task like for minitest or rspec, that would be great. See https://salsa.debian.org/ruby-team/ruby-sidekiq-cron/blob/master/debian/ruby-tests.rake and https://salsa.debian.org/ruby-team/ruby-hashie/blob/master/debian/ruby-tests.rake for examples. This is the implementation https://salsa.debian.org/ruby-team/gem2deb/tree/master/lib/gem2deb/rake and which uses https://salsa.debian.org/ruby-team/ruby-rspec/blob/master/rspec-core/lib/rspec/core/rake_task.rb I'm not a ruby programmer (I only do packaging of ruby gems for debian, which only needs very minimal level of ruby), so I won't be able to implement it myself.

**Comment by geemus** [comment]
Got it, thanks for the details. I don't think I'll have a chance to get to it soon, but this is very helpful for when I (or someone anyway) gets back to it.
